runtime: python311
entrypoint: gunicorn -b :$PORT main_cloud:app

env_variables:
  GOOGLE_CLOUD_PROJECT: "nationalgis"
  STORAGE_BUCKET: "national-4h-gis-team-data"
  SECRET_KEY: "your-secret-key-here"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto 